version: "3.8"

services:

  monitor:
    environment:
      - BROADCAST_PORT=4562
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/monitoring/index.js
    ports:
      - "3000:3000"
    depends_on:
      - peer

  peer:
    environment:
      - BROADCAST_PORT=4562
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/peer/index.js
    deploy:
      replicas: 3