version: "3.8"

services:

  monitor:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/monitoring/index.js
    depends_on:
      - peer

  peer:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node build/client/client.js
    deploy:
      replicas: 3